remote_theme: TaylanTatli/Moon

# Site
title:              Iran R. Roman
bio:                'Theoretical Neuroscience | Machine Perception | AI'
description:        ""
reading_time:       false
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/pic-big.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US

# Social
github-url:         iranroman
scholar:            W_PoFfkAAAAJ
linkedin:           iran-roman
youtube-channel:    UCP_UydM0eiFauT5N2IzUPIQ
